services:
  - type: web
    name: image-label-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: label_app.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: image-label-app.onrender.com
